# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-25 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tenddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tstartdate',
            field=models.DateField(),
        ),
    ]
