# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_re', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='anon', max_length=255),
        ),
    ]
