# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='n_id',
        ),
    ]
