# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_dj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auser',
            name='password',
            field=models.CharField(default='0000000', max_length=255),
        ),
    ]
